<?php

/**
 * @file
 * Contains design.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function design_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the design module.
    case 'help.page.design':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
